//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureASPProcject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneRefBrands
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhoneRefBrands()
        {
            this.PhoneDetail = new HashSet<PhoneDetail>();
        }
    
        public int PhoneRefBrandID { get; set; }
        public string PhoneRefBrandName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhoneDetail> PhoneDetail { get; set; }
    }
}
