//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureASPProcject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneDetail
    {
        public int PhoneID { get; set; }
        public string PhoneDescription { get; set; }
        public Nullable<int> PhoneBrandID { get; set; }
        public string PhoneColor { get; set; }
    
        public virtual PhoneRefBrands PhoneRefBrands { get; set; }
    }
}
